const MONGODB_URI = process.env.MONGODB_URI;
const PORT = process.env.PORT;
const PRODUCT_PER_PAGE = process.env.PRODUCT_PER_PAGE;

const REFRESH_TOKEN_SECRET = process.env.REFRESH_TOKEN_SECRET;
const ACCESS_TOKEN_SECRET = process.env.ACCESS_TOKEN_SECRET;
const REFRESH_TOKEN_EXPIRY = process.env.REFRESH_TOKEN_EXPIRY;
const ACCESS_TOKEN_EXPIRY = process.env.ACCESS_TOKEN_EXPIRY;
const BCRYPT_SALT_ROUND = parseInt(process.env.BCRYPT_SALT_ROUND);

const TWILIO_MESSAGE_SERVICE_SID = process.env.TWILIO_MESSAGE_SERVICE_SID;
const TWILLIO_AUTH_TOKEN = process.env.TWILLIO_AUTH_TOKEN;
const TWILLIO_ACCOUNT_SID = process.env.TWILLIO_ACCOUNT_SID;
const TWILIO_SENDER_PHONE_NUMBER = parseInt(
  process.env.TWILIO_SENDER_PHONE_NUMBER
);

const NODEMAILER_EMAIL_USER = process.env.NODEMAILER_EMAIL_USER;
const NODEMAILER_EMAIL_PASSWORD = process.env.NODEMAILER_EMAIL_PASSWORD;

const CLOUDNARY_API_KEY = process.env.CLOUDNARY_API_KEY;
const CLOUDNARY_API_SECREAT = process.env.CLOUDNARY_API_SECREAT;
const CLOUDNARY_CLOUD_NAME = process.env.CLOUDNARY_CLOUD_NAME;

// RAZORPAY -CNFIG
const RAZORPAY_API_KEY = process.env.RAZORPAY_API_KEY;
const RAZORPAY_API_SECRET = process.env.RAZORPAY_API_SECRET;

// export
export {
  MONGODB_URI,
  PORT,
  PRODUCT_PER_PAGE,
  REFRESH_TOKEN_SECRET,
  ACCESS_TOKEN_SECRET,
  REFRESH_TOKEN_EXPIRY,
  ACCESS_TOKEN_EXPIRY,
  BCRYPT_SALT_ROUND,
  TWILIO_MESSAGE_SERVICE_SID,
  TWILLIO_AUTH_TOKEN,
  TWILLIO_ACCOUNT_SID,
  TWILIO_SENDER_PHONE_NUMBER,
  NODEMAILER_EMAIL_USER,
  NODEMAILER_EMAIL_PASSWORD,
  CLOUDNARY_API_KEY,
  CLOUDNARY_API_SECREAT,
  CLOUDNARY_CLOUD_NAME,
  RAZORPAY_API_KEY,
  RAZORPAY_API_SECRET,
};
